### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by webhaikal**

### CODE REVIEW

**Comment by webhaikal** [comment]
Just something I thought we would need

**Comment by thewisenerd** [comment]
1. the twrp at `dl.twrp.me` is outdated, with a kernel that doesn't support f2fs, etc. need to update that link to a relatively _stable_ recovery that supports f2fs, has vibration fixed (jk), and has partition list order fixed (jk).

2. `flash_all.bat` or `flash_all.sh` depending on your operating system. idk if this wipes internal memory. update accordingly.

3. where is point 3? :stuck_out_tongue: 

6. remove this for now? we'll add back if and when necessary. or maybe merge with point 7. donations mainly would be required if and when we decide to get servers for building. if someone can donate servers as well, ¯\_(ツ)_/¯

**Comment by webhaikal** [comment]
@thewisenerd where is latest twrp?

**Comment by thewisenerd** [comment]
fit this in someplace

| firmware | kernel | status |
|:--------:|:------:|:------:|
|   6.x    |   6.x  |    ✔   |
|   6.x    |   8.x  |    ✱   |
|   8.x    |   6.x  |    ✖   |
|   8.x    |   8.x  |    ✔   |

 - ✔ works
 - ✖ doesn't work at all
 - ✱ works but be warned

markdown: 

```
| firmware | kernel | status |
|:--------:|:------:|:------:|
|   6.x    |   6.x  |    ✔   |
|   6.x    |   8.x  |    ✱   |
|   8.x    |   6.x  |    ✖   |
|   8.x    |   8.x  |    ✔   |

 - ✔ works
 - ✖ doesn't work at all
 - ✱ works but be warned
```

**Pull request closed without merging**
